version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build and Tag Docker Images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-api-feed linhbui167/udagram-api-feed:v1
            docker tag udagram-api-user linhbui167/udagram-api-user:v1
            docker tag udagram-reverseproxy linhbui167/udagram-reverseproxy:v1
            docker tag udagram-frontend linhbui167/udagram-frontend:v1
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push linhbui167/udagram-api-feed:v1
            docker push linhbui167/udagram-api-user:v1
            docker push linhbui167/udagram-reverseproxy:v1
            docker push linhbui167/udagram-frontend:v1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Adjust this to match your main branch name
